### ISSUE TITLE
visual reports not generated

### ISSUE THREAD

**Issue by jbwexler** [PeerHerholz/BIDSonym#20]
I tried running BIDSonym both via singularity on TACC and via docker locally. With both installations and on two different datasets, no visual html reports were generated. Everything else seemed to work fine, including various .csv files, de-id niftis, etc. Perhaps there's an issue with my command? This is an example singularity command I used:

singularity run --cleanenv \
    /work/03201/jbwexler/lonestar/jbwexler/singularity_images/bidsonym_latest.simg \
    /scratch/03201/jbwexler/quickshear/IN_PROGRESS/ds001493-download \
    group \
    --deid quickshear

**Comment by PeerHerholz** [comment]
Hi @jbwexler,

thank you very much for posting this issue.

The documentation is unfortunately misleading, as the reports underwent a change and are currently not generated. This will be updated next week and I'll post respective updates here.

**Comment by jbwexler** [comment]
Thanks!

**Comment by complexbrains** [comment]
Hi @PeerHerholz I am having the same issue, everything worked as they should be but missing html files, unfortunately. I was wondering whether it is still a work in progress or is there a way to produce such a QA report some sort of, please? Thank you in advance.

**Comment by PeerHerholz** [comment]
Hi there,

The html report functionality was removed due to inconsistencies concerning their generation. The feature will be re-introduced after [the corresponding functionality of niworkflows](https://www.nipreps.org/niworkflows/master/api/niworkflows.reports.core.html) is updated. In the meantime, BIDSonym will however still produce the respective graphics, etc. and place them in the corresponding subject folders.

Cheers, Peer
