### ISSUE TITLE
Sample report in the Outputs Document is Broken

### ISSUE THREAD

**Issue by complexbrains** [PeerHerholz/BIDSonym#44]
**Describe the bug**

[Sample report](https://peerherholz.github.io/BIDSonym/_static/sample_report.html) in [Outputs document](https://peerherholz.github.io/BIDSonym/outputs.html) is broken.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/45263281/104034710-266ebd00-51c9-11eb-99a1-44872393b188.png)

**OS/environment (please provide precise information on your OS/environment):**
Windows 10 with Chrome and Firefox browser. 

**Additional context**

**Comment by PeerHerholz** [comment]
Hi there @complexbrains,

thanks for raising this issue. The `html report` functionality was removed due to inconsistencies concerning their generation. The feature will be re-introduced after [the corresponding functionality of niworkflows](https://www.nipreps.org/niworkflows/master/api/niworkflows.reports.core.html) is updated.  In the meantime, `BIDSonym` will however still produce the respective graphics, etc. and place them in the corresponding `subject` folders.

Cheers, Peer
